language: node_js

node_js:
   - node # will use latest node

before_script: # commands to run before the build step
   - npm install -g --silent @angular/cli

script: # the build step
- '#!/bin/bash

  set -ev

  if [ ${TRAVIS_SECURE_ENV_VARS} = "true" ]; then
      docker run project-container "ng lint";
      docker run project-container "ng test --browser PhantomJS --watch=false";
      docker run project-container "ng build --prod";
      docker-compose run ui-tests
  else
      ng lint;
      ng test --browser PhantomJS --watch=false;
      ng build --prod;
  fi

  exit 0;'


notifications:
  email: # only receive email when the build status changes (someone broke the build!) 
    on_failure: change
    on_success: change 
deploy:
  provider: heroku
  api-key: 
      secure: $HEROKU_API_KEY
  app: recrutamento-fe