language: node_js

node_js:
   - node # will use latest node

before_script: # commands to run before the build step
   - npm install -g --silent @angular/cli

script: # the build step
- '#!/bin/bash

  set -ev

  if [ ${TRAVIS_SECURE_ENV_VARS} = "true" ]; then
      docker run project-container "npm run test";
      docker run project-container "npm run test:lint";
      docker-compose run ui-tests;
  else
      npm run test;
      npm run test:lint;
  fi

  exit 0;'


notifications:
  email: # only receive email when the build status changes (someone broke the build!) 
    on_failure: change
    on_success: change 
deploy:
  provider: heroku
  api-key: 
      secure: $HEROKU_API_KEY
  app: recrutamento-fe